name: muli_mobile_task
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^6.1.3
  rxdart: ^0.25.0
  cupertino_icons: ^1.0.2
  connectivity: ^3.0.2
  fluro: ^2.0.3


  core:
    path: libraries/core
  navigation:
    path: libraries/navigation
  search:
    path: features/search

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/

